export const THRESHOLDS = {
  OVERLOAD_PERCENT: 90,
  UNDERUTILIZATION_PERCENT: 40,
  PENDING_CONFIRMATIONS_COUNT: 10,
  EXPECTED_NO_SHOW_RATE: 0.25,
  MAX_BANNER_SIGNALS: 3,
} as const

export const PRIORITIES = {
  OVERLOAD_CRITICAL: 95,
  OVERLOAD_WARNING: 80,
  PENDING_SEVERE: 75,
  PENDING_WARNING: 60,
  UNDERUTIL_SEVERE: 25,
  UNDERUTIL_WARNING: 15,
} as const